language: objective-c
xcode_project: CleanroomDateTime.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init
  PHONE_SIM=
  TV_SIM=

install:
  gem install xcpretty

script:
- open -a "simulator" --args -CurrentDeviceUDID ""
- set -o pipefail && xcodebuild -project CleanroomDateTime.xcodeproj -scheme CleanroomDateTime-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDateTime.xcodeproj -scheme CleanroomDateTime-OSX -destination 'platform=macOS' clean test | xcpretty
- open -a "simulator" --args -CurrentDeviceUDID ""
- set -o pipefail && xcodebuild -project CleanroomDateTime.xcodeproj -scheme CleanroomDateTime-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDateTime.xcodeproj -scheme CleanroomDateTime-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' clean build | xcpretty

